### ISSUE TITLE
add these sources on diversity

### ISSUE THREAD

**Issue by gabriben** [svrijenhoek/dart#187]
- [ ] Diversity in Sociotechnical Machine Learning Systems (Fazelpour and De-Arteaga)
- [x] Diversity and Inclusion Metrics in Subset Selection (Mitchell et al.)
- [ ] Public enemy no. 1? Understanding media representations of outlier views on climate change (Boykoff)
- [ ] works by Naomi Oreskes
- [x] Multiple diversity concepts and their ethical-epistemic implications (Steel et al.)

**Comment by svrijenhoek** [comment]
I don't think it makes sense to include sources on Critical theory specifically, that is grounds for another paper. Will add the Fazelpour, Mitchell and Steel papers.

**Comment by gabriben** [comment]
would you add this paper in descriptive or normative?
https://link.springer.com/article/10.1007/s11257-018-9205-x

**Comment by gabriben** [comment]
which ones are critical theory?

**Comment by gabriben** [comment]
https://www.aeaweb.org/articles?id=10.1257/aer.20190390
same for this one, could be added in normative

**Comment by svrijenhoek** [comment]
added the first one to the descriptive section, and the second to 'identifying user preferences' in the introduction.
